### ISSUE TITLE
Keyword filters not working for issueSymbolIdentifier field in weekly_summary dataset

### ISSUE THREAD

**Issue by Djangu-algo** [chencindyj/finra_api_queries#1]
Using the following code (token is produced by retrieve_api_token function)

```python
date_filter_inputs = [{'startDate': '2023-07-03', 'endDate': '2023-07-03', 'fieldName': 'lastUpdateDate'}]

filters_input = {'totalWeeklyShareQuantity':['>= 200000'],'issueSymbolIdentifier':['SU']}

finra_api_queries.retrieve_dataset(dataset_name="weekly_summary",my_access_token=token,rows_returned=10000000,date_filter = date_filter_inputs,filters = filters_input)
``` 

expected the output to contain only fields where issueSymbolIdentifier is 'SU', however all symbols are returned. Flagging this early before any further exploration of the API has been done.

On further API testing using curl, the following output was produced (in Windows)

```
curl -L -d "{ \"compareFilters\": [ { \"compareType\": \"EQUAL\", \"fieldName\": \" issueSymbolIdentifier \", \"fieldValue\": \"SU\" } ] ,\"limit\":5 } " -H "Content-Type: application/json" -X POST https://api.finra.org/data/group/otcMarket/name/weeklySummary
``` 
output is

"issueSymbolIdentifier","issueName","firmCRDNumber","MPID","marketParticipantName","tierIdentifier","tierDescription","summaryStartDate","totalWeeklyTradeCount","totalWeeklyShareQuantity","productTypeCode","summaryTypeCode","weekStartDate","lastUpdateDate","initialPublishedDate","lastReportedDate"
"SU","Suncor Energy, Inc.",,"JPMX","JPMX JPM-X","T2","NMS Tier 2","2018-08-20","274","28380",,"ATS_W_SMBL_FIRM","2018-08-20","2018-09-24","2018-09-24","2018-08-24"
"SU","Suncor Energy, Inc.",,"ITGP","ITGP POSIT","T2","NMS Tier 2","2018-08-20","112","14200",,"ATS_W_SMBL_FIRM","2018-08-20","2018-09-24","2018-09-24","2018-08-24"
"SU","Suncor Energy, Inc.",,"CROS","CROS CROSSFINDER","T2","NMS Tier 2","2018-08-20","1051","106600",,"ATS_W_SMBL_FIRM","2018-08-20","2018-09-24","2018-09-24","2018-08-24"
"SU","Suncor Energy, Inc.",,"CXCX","CXCX CITI CROSS","T2","NMS Tier 2","2018-08-20","75","7678",,"ATS_W_SMBL_FIRM","2018-08-20","2018-09-24","2018-09-24","2018-08-24"
"SU","Suncor Energy, Inc.",,"MSPL","MSPL MS POOL (ATS-4)","T2","NMS Tier 2","2018-08-20","719","108700",,"ATS_W_SMBL_FIRM","2018-08-20","2018-09-24","2018-09-24","2018-08-24"

the following works (values simply hard coded)

```python
requests.post(
    f"https://api.finra.org/data/group/otcMarket/name/weeklySummary",
    headers={"Authorization": "Bearer " + token, "Accept": "application/json"},
    json={
        "compareFilters": [
            {
                "compareType": "equal",
                "fieldName": "issueSymbolIdentifier",
                "fieldValue": "SU",
            }
        ],
        "limit": 20000,
    },
)
```

**Comment by chencindyj** [comment]
Thanks for catching that. I updated the package to 1.2.1 with the fix.
